#!/bin/sh

set -e

. ./config.conf


KERNEL_FLAVORS="amd64"


lb config noauto \
    --architectures "$ARCH" \
    --mode debian \
    --distribution "$BASECODENAME" \
    --parent-distribution "$BASECODENAME" \
    --linux-packages "linux-image linux-headers" \
    --linux-flavours "$KERNEL_FLAVORS" \
    --bootappend-live "boot=live config username=root user-fullname='StrawberryOS Live User' splash bgrt_disable" \
    \
    --parent-archive-areas "main contrib non-free non-free-firmware" \
    --parent-mirror-bootstrap "$MIRROR_URL" \
    --parent-mirror-chroot-security "http://deb.debian.org/debian-security" \
    --parent-mirror-binary-security "http://deb.debian.org/debian-security" \
    --parent-mirror-binary "https://deb.debian.org/debian" \
    \
    --archive-areas "main contrib non-free non-free-firmware" \
    --mirror-bootstrap "$MIRROR_URL" \
    --mirror-chroot-security "http://deb.debian.org/debian-security" \
    --mirror-binary-security "http://deb.debian.org/debian-security" \
    --mirror-binary "https://deb.debian.org/debian" \
    \
    --keyring-packages debian-keyring \
    --apt-options "--yes --option Acquire::Retries=5 --option Acquire::http::Timeout=100" \
    --apt-recommends false \
    --cache-packages false \
    --uefi-secure-boot enable \
    --binary-images iso-hybrid \
    --iso-application "$NAME" \
    --iso-volume "$NAME" \
    --firmware-binary false \
    --firmware-chroot false \
    --security true \
    --updates false \
    --debootstrap-options "--exclude=pinephone-tweaks,mobile-tweaks-common,librem5-tweaks,pinetab-tweaks --include=apt-transport-https,ca-certificates,openssl,busybox-static" \
    --checksums md5 \
    --clean \
    "${@}"


# replace channel and suite
# sed -i "s/@CHANNEL/$CHANNEL/" config/archives/*.list*
# sed -i "s/@BASECODENAME/$BASECODENAME/" config/archives/*.list*

DATE=$(date +%Y%m%d)
sed -i "s/@CHANNEL/$CHANNEL/" config/includes.binary/.disk/info
sed -i "s/@FULLCODENAME/$FULLCODENAME/" config/includes.binary/.disk/info
sed -i "s/@CODENAME/$CODENAME/" config/includes.binary/.disk/info
sed -i "s/@ARCH/$ARCH/" config/includes.binary/.disk/info
sed -i "s/@DISTRO_NAME/$NAME/" config/includes.binary/.disk/info
sed -i "s/@VERSION/$VERSION/" config/includes.binary/.disk/info
sed -i "s/@DATE/$DATE/" config/includes.binary/.disk/info

sed -i "s/@DISTRO_NAME/$NAME/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@VERSION/$VERSION/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@CHANNEL/$CHANNEL/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@FULLCODENAME/$FULLCODENAME/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@CODENAME/$CODENAME/" config/hooks/live/004-set-os-info.chroot
sed -i "s/@BASECODENAME/$BASECODENAME/" config/hooks/live/004-set-os-info.chroot

sed -i "s/@DISTRO_NAME/$NAME/" config/bootloaders/grub-pc/grub.cfg
sed -i "s/@VERSION/$VERSION/" config/bootloaders/grub-pc/grub.cfg
sed -i "s/@CHANNEL/$CHANNEL/" config/bootloaders/grub-pc/grub.cfg
sed -i "s/@FULLCODENAME/$FULLCODENAME/" config/bootloaders/grub-pc/grub.cfg
sed -i "s/@CODENAME/$CODENAME/" config/bootloaders/grub-pc/grub.cfg
sed -i "s/@BASECODENAME/$BASECODENAME/" config/bootloaders/grub-pc/grub.cfg

# sed -i "s/@XORG_HWE/$XORG_HWE/" config/package-lists/desktop.list.chroot_install
