name: StrawberryOS snapshot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4
    
    - name: Install needed packages
      run: apt update && apt install debootstrap git -y

    - name: Build ISO
      run: |
        cd /
        git clone https://github.com/Strawberry-Foundations/sbos-live-iso
        cd sbos-live-iso
        bash ./ghbuild.sh

    - uses: actions/upload-artifact@v4
      with:
        name: StrawberryOS snapshot
        path: builds/
